### ISSUE TITLE
Compare test run UI bug for suite with no reference

### ISSUE THREAD

**Issue by max-arthurai** [arthur-ai/bench#114]
The QA Correctness scorer (as well as other scorers) does not require/allow reference outputs, so I didn't include them in my test suite. But it looks like the compare test table still has a column for REFERENCE OUTPUTS even when my suite lacks them, which causes an accidental shift in all the data one column to the left:

<img width="1486" alt="Screenshot 2024-03-27 at 11 49 43 AM" src="https://github.com/arthur-ai/bench/assets/115359769/487b1aa6-2962-4ae9-85a2-0938a931f3f5">

**Comment by cheungrowan** [comment]
Hi @max-arthurai thanks for opening this issue. Please see #116 for a potential fix
