### ISSUE TITLE
Type object is not subscriptable

### ISSUE THREAD

**Issue by thinkinsysdev** [arthur-ai/bench#68]
Getting error when running the first import statement - from arthur_bench.run.testsuite import TestSuite

Error:

SCORING_METHOD_CLASS_MAP: Dict[str, type[Scorer]] = {
TypeError: ‘type’ object is not subscriptable

Mac M1 Max Ventura 13.5
python 3.8.13

any ideas

**Comment by max-arthurai** [comment]
Hi @thinkinsysdev 

Try creating a fresh environment with python 3.9 instead of python 3.8. Then try rerunning the same code with your new environment.

We use type subscripting in our python code which requires python 3.9+
