### ISSUE TITLE
UserValueError: cannot reference custom scorer by string. please provide instantiated scorer

### ISSUE THREAD

**Issue by aaprajo** [arthur-ai/bench#77]
from arthur_bench.run.testsuite import TestSuite
suite = TestSuite(
    "bench_quickstart", 
    "exact_match",
    input_text_list=["What year was FDR elected?", "What is the opposite of down?"], 
    reference_output_list=["1932", "up"]
)
suite.run("quickstart_run", candidate_output_list=["1932", "up is the opposite of down"])

existing_suite = TestSuite("bench_quickstart", "exact_match")
existing_suite.run("quickstart_new_run", candidate_output_list=["1936", "up"])

---------------------------------------------------------------------------
UserValueError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18792/3237977438.py in <module>
----> 1 existing_suite = TestSuite("bench_quickstart", "exact_match")
      2 existing_suite.run("quickstart_new_run", candidate_output_list=["1936", "up"])

~\anaconda3\lib\site-packages\arthur_bench\run\testsuite.py in __init__(self, name, scoring_method, description, reference_data, reference_data_path, input_column, reference_column, input_text_list, reference_output_list, client)
    103             if self._data.scoring_method.type == ScoringMethodType.Custom:
    104                 if isinstance(scoring_method, str):
--> 105                     raise UserValueError(
    106                         "cannot reference custom scorer by string. please provide "
    107                         "instantiated scorer"

UserValueError: cannot reference custom scorer by string. please provide instantiated scorer
​

**Comment by cheungrowan** [comment]
hi @aaprajo I am having trouble reproducing this error, are there any other steps that you took to reach this state?

Additionally, if you can attach the test suite configuration file located at your `{BENCH_FILE_DIR}/bench_runs/bench_quickstart/suite.json`, that could be useful to help debug
